services:
  postgres:
    image: postgres:16
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-postgrest.sql:/docker-entrypoint-initdb.d/init-postgrest.sql

  mailhog:
    image: mailhog/mailhog
    container_name: local_mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    depends_on:
      - postgres
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://devuser:devpass@local_postgres:5432/devdb
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMA: public
      PGRST_SERVER_CORS: "true"
      PGRST_SERVER_PROXY_URI: http://localhost:3000
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
     
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - postgrest

volumes:
  pgdata: