version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-postgrest-test.sql:/docker-entrypoint-initdb.d/init-postgrest-test.sql

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    depends_on:
      - postgres
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMA: public

  mailrise:
    image: soxoj/mailrise
    container_name: mailrise
    restart: always
    environment:
      SMTP_HOST: postfix-relay
      SMTP_PORT: 25
      SMTP_TLS: "false"

  postfix-relay:
    image: boky/postfix
    container_name: postfix-relay
    restart: always
    environment:
      - RELAYHOST=relay-cluster-eu01.hornetsecurity.com
      - RELAYHOST_PORT=25 # 25 for TLS/STARTTLS (recommended)
      - SMTP_TLS_SECURITY_LEVEL=may # Enforces STARTTLS if server supports it

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80" #Flutter Web HTTP
      - "443:443" #Flutter Web HTTPS
      - "8081:8081" #Postgrest API
      - "8080:8080" #Email API
    volumes:
      - ./Caddyfile.test:/etc/caddy/Caddyfile
      - ../build/web:/web
    depends_on:
      - postgrest

volumes:
  pgdata:
