version: "3.8"

services:
  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?sslmode=disable"
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMA: public

  email-service:
    build: ./email-service
    container_name: email-service
    depends_on:
      - postfix-relay

  postfix-relay:
    image: boky/postfix
    container_name: postfix-relay
    restart: always
    environment:
      - RELAYHOST=relay-cluster-eu01.hornetsecurity.com
      - RELAYHOST_PORT=25 # 25 for TLS/STARTTLS (recommended)
      - SMTP_TLS_SECURITY_LEVEL=may # Enforces STARTTLS if server supports it
      - ALLOW_EMPTY_SENDER_DOMAINS=true

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80" #Flutter Web HTTP
      - "443:443" #Flutter Web HTTPS
      - "8081:8081" #Postgrest API
      - "8080:8080" #Email API
      - "8083:8083" #ZMI Monitor
    volumes:
      - ./Caddyfile.test:/etc/caddy/Caddyfile
      - ../build/web:/web
    depends_on:
      - postgrest

  zmi-monitor:
    build:
      context: ./zmi-monitor
      dockerfile: Dockerfile
    container_name: zmi_monitor
    restart: always
    environment:
      - TARGET_URL=https://webintern.bssb.bayern:56400/rest/zmi/api/serverping
      - EXPECTED_HTTP_CODE=200
      - MAX_RESPONSE_TIME=5.0
      - CONNECT_TIMEOUT=3
      - MAX_TIME=10
      - LOG_FILE=/var/www/html/data/https_monitor.csv
      - TZ=Europe/Berlin
    volumes:
      - zmi_data:/var/www/html/data

volumes:
  zmi_data:
