version: "3.8"

services:
  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?sslmode=disable"
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMA: public
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_JWT_ROLE_CLAIM_KEY: .role

  email-service:
    build: ./email-service
    container_name: email-service
    depends_on:
      - postfix-relay

  token-service:
    build: ./token-service
    container_name: token-service
    restart: always
    environment:
      - TOKEN_SERVER_PROTOCOL=https
      - TOKEN_SERVER_HOST=webintern.bssb.bayern
      - TOKEN_SERVER_PORT=50211
      - TOKEN_SERVER_PATH=rest/zmi/token
      - PORT=3002
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=24h
      - ZMI_USERNAME=${ZMI_USERNAME}
      - ZMI_PASSWORD=${ZMI_PASSWORD}

  postfix-relay:
    image: boky/postfix
    container_name: postfix-relay
    restart: always
    environment:
      - RELAYHOST=relay-cluster-eu01.hornetsecurity.com
      - RELAYHOST_PORT=25 # 25 for TLS/STARTTLS (recommended)
      - SMTP_TLS_SECURITY_LEVEL=may # Enforces STARTTLS if server supports it
      - ALLOW_EMPTY_SENDER_DOMAINS=true

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "443:443" #Flutter Web HTTPS
      - "8081:8081" #Postgrest API
      - "8080:8080" #Email API
      - "8082:8082" #Token API
    environment:
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
      - ../build/web:/web
    depends_on:
      - postgrest
