// Mocks generated by Mockito 5.4.6 from annotations
// in meinbssb/test/unit/screens/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:typed_data' as _i11;

import 'package:meinbssb/models/bank_data.dart' as _i22;
import 'package:meinbssb/models/bezirk_data.dart' as _i28;
import 'package:meinbssb/models/contact_data.dart' as _i16;
import 'package:meinbssb/models/disziplin_data.dart' as _i23;
import 'package:meinbssb/models/fremde_verband_data.dart' as _i25;
import 'package:meinbssb/models/gewinn_data.dart' as _i27;
import 'package:meinbssb/models/pass_data_zve_data.dart' as _i14;
import 'package:meinbssb/models/passdaten_akzept_or_aktiv_data.dart' as _i13;
import 'package:meinbssb/models/person_data.dart' as _i17;
import 'package:meinbssb/models/register_schulungen_teilnehmer_response_data.dart'
    as _i7;
import 'package:meinbssb/models/result_data.dart' as _i26;
import 'package:meinbssb/models/schulung_data.dart' as _i18;
import 'package:meinbssb/models/schulungsart_data.dart' as _i19;
import 'package:meinbssb/models/schulungstermin_data.dart' as _i20;
import 'package:meinbssb/models/schulungstermine_zusatzfelder_data.dart'
    as _i21;
import 'package:meinbssb/models/user_data.dart' as _i12;
import 'package:meinbssb/models/verein_data.dart' as _i24;
import 'package:meinbssb/models/zweitmitgliedschaft_data.dart' as _i15;
import 'package:meinbssb/services/api/auth_service.dart' as _i5;
import 'package:meinbssb/services/api/starting_rights_service.dart' as _i9;
import 'package:meinbssb/services/api_service.dart' as _i8;
import 'package:meinbssb/services/core/cache_service.dart' as _i6;
import 'package:meinbssb/services/core/config_service.dart' as _i3;
import 'package:meinbssb/services/core/email_service.dart' as _i4;
import 'package:meinbssb/services/core/image_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImageService_0 extends _i1.SmartFake implements _i2.ImageService {
  _FakeImageService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfigService_1 extends _i1.SmartFake implements _i3.ConfigService {
  _FakeConfigService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmailService_2 extends _i1.SmartFake implements _i4.EmailService {
  _FakeEmailService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_3 extends _i1.SmartFake implements _i5.AuthService {
  _FakeAuthService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCacheService_4 extends _i1.SmartFake implements _i6.CacheService {
  _FakeCacheService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_5 extends _i1.SmartFake implements Duration {
  _FakeDuration_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterSchulungenTeilnehmerResponse_6 extends _i1.SmartFake
    implements _i7.RegisterSchulungenTeilnehmerResponse {
  _FakeRegisterSchulungenTeilnehmerResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i8.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ImageService get imageService =>
      (super.noSuchMethod(
            Invocation.getter(#imageService),
            returnValue: _FakeImageService_0(
              this,
              Invocation.getter(#imageService),
            ),
          )
          as _i2.ImageService);

  @override
  _i3.ConfigService get configService =>
      (super.noSuchMethod(
            Invocation.getter(#configService),
            returnValue: _FakeConfigService_1(
              this,
              Invocation.getter(#configService),
            ),
          )
          as _i3.ConfigService);

  @override
  _i4.EmailService get emailService =>
      (super.noSuchMethod(
            Invocation.getter(#emailService),
            returnValue: _FakeEmailService_2(
              this,
              Invocation.getter(#emailService),
            ),
          )
          as _i4.EmailService);

  @override
  _i5.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_3(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i5.AuthService);

  @override
  _i6.CacheService get cacheService =>
      (super.noSuchMethod(
            Invocation.getter(#cacheService),
            returnValue: _FakeCacheService_4(
              this,
              Invocation.getter(#cacheService),
            ),
          )
          as _i6.CacheService);

  @override
  void setStartingRightsService(_i9.StartingRightsService? service) =>
      super.noSuchMethod(
        Invocation.method(#setStartingRightsService, [service]),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<bool> hasInternet() =>
      (super.noSuchMethod(
            Invocation.method(#hasInternet, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  Duration getCacheExpirationDuration() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheExpirationDuration, []),
            returnValue: _FakeDuration_5(
              this,
              Invocation.method(#getCacheExpirationDuration, []),
            ),
          )
          as Duration);

  @override
  _i10.Future<String?> getCachedUsername() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUsername, []),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<_i11.Uint8List> fetchSchuetzenausweis(int? personId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSchuetzenausweis, [personId]),
            returnValue: _i10.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
          )
          as _i10.Future<_i11.Uint8List>);

  @override
  _i10.Future<Map<String, dynamic>> register({
    required String? firstName,
    required String? lastName,
    required String? passNumber,
    required String? email,
    required String? personId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #firstName: firstName,
              #lastName: lastName,
              #passNumber: passNumber,
              #email: email,
              #personId: personId,
            }),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> passwordReset(String? passNumber) =>
      (super.noSuchMethod(
            Invocation.method(#passwordReset, [passNumber]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> finalizeResetPassword(
    String? token,
    String? personId,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#finalizeResetPassword, [
              token,
              personId,
              newPassword,
            ]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> myBSSBPasswortAendern(
    int? personId,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#myBSSBPasswortAendern, [personId, newPassword]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<_i12.UserData?> fetchPassdaten(int? personId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPassdaten, [personId]),
            returnValue: _i10.Future<_i12.UserData?>.value(),
          )
          as _i10.Future<_i12.UserData?>);

  @override
  _i10.Future<_i13.PassdatenAkzeptOrAktiv?>
  fetchPassdatenAkzeptierterOderAktiverPass(int? personId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPassdatenAkzeptierterOderAktiverPass, [
              personId,
            ]),
            returnValue: _i10.Future<_i13.PassdatenAkzeptOrAktiv?>.value(),
          )
          as _i10.Future<_i13.PassdatenAkzeptOrAktiv?>);

  @override
  _i10.Future<bool> bssbAppPassantrag(
    List<Map<String, dynamic>>? zves,
    int? passdatenId,
    int? personId,
    int? erstVereinId,
    int? digitalerPass,
    int? antragsTyp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bssbAppPassantrag, [
              zves,
              passdatenId,
              personId,
              erstVereinId,
              digitalerPass,
              antragsTyp,
            ]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<_i14.PassDataZVE>> fetchPassdatenZVE(
    int? passdatenId,
    int? personId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPassdatenZVE, [passdatenId, personId]),
            returnValue: _i10.Future<List<_i14.PassDataZVE>>.value(
              <_i14.PassDataZVE>[],
            ),
          )
          as _i10.Future<List<_i14.PassDataZVE>>);

  @override
  _i10.Future<bool> deleteMeinBSSBLogin(int? webloginId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMeinBSSBLogin, [webloginId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> updateKritischeFelderUndAdresse(_i12.UserData? userData) =>
      (super.noSuchMethod(
            Invocation.method(#updateKritischeFelderUndAdresse, [userData]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<_i15.ZweitmitgliedschaftData>> fetchZweitmitgliedschaften(
    int? personId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchZweitmitgliedschaften, [personId]),
            returnValue: _i10.Future<List<_i15.ZweitmitgliedschaftData>>.value(
              <_i15.ZweitmitgliedschaftData>[],
            ),
          )
          as _i10.Future<List<_i15.ZweitmitgliedschaftData>>);

  @override
  _i10.Future<List<_i15.ZweitmitgliedschaftData>> fetchZweitmitgliedschaftenZVE(
    int? personId,
    int? passStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchZweitmitgliedschaftenZVE, [
              personId,
              passStatus,
            ]),
            returnValue: _i10.Future<List<_i15.ZweitmitgliedschaftData>>.value(
              <_i15.ZweitmitgliedschaftData>[],
            ),
          )
          as _i10.Future<List<_i15.ZweitmitgliedschaftData>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> fetchKontakte(int? personId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchKontakte, [personId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<bool> addKontakt(_i16.Contact? contact) =>
      (super.noSuchMethod(
            Invocation.method(#addKontakt, [contact]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> deleteKontakt(_i16.Contact? contact) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKontakt, [contact]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> clearAllPassdatenCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllPassdatenCache, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> clearPassdatenCache(int? personId) =>
      (super.noSuchMethod(
            Invocation.method(#clearPassdatenCache, [personId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i17.Person>> fetchAdresseVonPersonID(int? personId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAdresseVonPersonID, [personId]),
            returnValue: _i10.Future<List<_i17.Person>>.value(<_i17.Person>[]),
          )
          as _i10.Future<List<_i17.Person>>);

  @override
  _i10.Future<List<_i18.Schulung>> fetchAbsolvierteSchulungen(int? personId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAbsolvierteSchulungen, [personId]),
            returnValue: _i10.Future<List<_i18.Schulung>>.value(
              <_i18.Schulung>[],
            ),
          )
          as _i10.Future<List<_i18.Schulung>>);

  @override
  _i10.Future<List<_i19.Schulungsart>> fetchSchulungsarten() =>
      (super.noSuchMethod(
            Invocation.method(#fetchSchulungsarten, []),
            returnValue: _i10.Future<List<_i19.Schulungsart>>.value(
              <_i19.Schulungsart>[],
            ),
          )
          as _i10.Future<List<_i19.Schulungsart>>);

  @override
  _i10.Future<List<_i20.Schulungstermin>> fetchAngemeldeteSchulungen(
    int? personId,
    String? abDatum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAngemeldeteSchulungen, [personId, abDatum]),
            returnValue: _i10.Future<List<_i20.Schulungstermin>>.value(
              <_i20.Schulungstermin>[],
            ),
          )
          as _i10.Future<List<_i20.Schulungstermin>>);

  @override
  _i10.Future<bool> isRegisterForThisSchulung(
    int? personId,
    int? schulungsterminId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isRegisterForThisSchulung, [
              personId,
              schulungsterminId,
            ]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<_i21.SchulungstermineZusatzfelder>>
  fetchSchulungstermineZusatzfelder(int? schulungsTerminId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSchulungstermineZusatzfelder, [
              schulungsTerminId,
            ]),
            returnValue:
                _i10.Future<List<_i21.SchulungstermineZusatzfelder>>.value(
                  <_i21.SchulungstermineZusatzfelder>[],
                ),
          )
          as _i10.Future<List<_i21.SchulungstermineZusatzfelder>>);

  @override
  _i10.Future<int> findePersonID2(String? name, String? passnummer) =>
      (super.noSuchMethod(
            Invocation.method(#findePersonID2, [name, passnummer]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<int> findePersonIDSimple(
    String? name,
    String? nachname,
    String? passnummer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findePersonIDSimple, [
              name,
              nachname,
              passnummer,
            ]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<List<_i20.Schulungstermin>> fetchSchulungstermine(
    String? abDatum,
    String? webGruppe,
    String? bezirk,
    String? fuerVerlaengerung,
    String? fuerVuelVerlaengerung,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSchulungstermine, [
              abDatum,
              webGruppe,
              bezirk,
              fuerVerlaengerung,
              fuerVuelVerlaengerung,
            ]),
            returnValue: _i10.Future<List<_i20.Schulungstermin>>.value(
              <_i20.Schulungstermin>[],
            ),
          )
          as _i10.Future<List<_i20.Schulungstermin>>);

  @override
  _i10.Future<void> clearAllSchulungenCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllSchulungenCache, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i20.Schulungstermin?> fetchSchulungstermin(
    String? schulungenTerminId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSchulungstermin, [schulungenTerminId]),
            returnValue: _i10.Future<_i20.Schulungstermin?>.value(),
          )
          as _i10.Future<_i20.Schulungstermin?>);

  @override
  _i10.Future<void> clearDisziplinenCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearDisziplinenCache, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i7.RegisterSchulungenTeilnehmerResponse>
  registerSchulungenTeilnehmer({
    required int? schulungTerminId,
    required _i12.UserData? user,
    required String? email,
    required String? telefon,
    required _i22.BankData? bankData,
    required List<Map<String, dynamic>>? felderArray,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerSchulungenTeilnehmer, [], {
              #schulungTerminId: schulungTerminId,
              #user: user,
              #email: email,
              #telefon: telefon,
              #bankData: bankData,
              #felderArray: felderArray,
            }),
            returnValue:
                _i10.Future<_i7.RegisterSchulungenTeilnehmerResponse>.value(
                  _FakeRegisterSchulungenTeilnehmerResponse_6(
                    this,
                    Invocation.method(#registerSchulungenTeilnehmer, [], {
                      #schulungTerminId: schulungTerminId,
                      #user: user,
                      #email: email,
                      #telefon: telefon,
                      #bankData: bankData,
                      #felderArray: felderArray,
                    }),
                  ),
                ),
          )
          as _i10.Future<_i7.RegisterSchulungenTeilnehmerResponse>);

  @override
  _i10.Future<void> clearSchulungenCache(int? personId) =>
      (super.noSuchMethod(
            Invocation.method(#clearSchulungenCache, [personId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> unregisterFromSchulung(int? schulungenTeilnehmerID) =>
      (super.noSuchMethod(
            Invocation.method(#unregisterFromSchulung, [
              schulungenTeilnehmerID,
            ]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> registerFromSchulung(int? personId, int? schulungId) =>
      (super.noSuchMethod(
            Invocation.method(#registerFromSchulung, [personId, schulungId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<_i23.Disziplin>> fetchDisziplinen() =>
      (super.noSuchMethod(
            Invocation.method(#fetchDisziplinen, []),
            returnValue: _i10.Future<List<_i23.Disziplin>>.value(
              <_i23.Disziplin>[],
            ),
          )
          as _i10.Future<List<_i23.Disziplin>>);

  @override
  _i10.Future<List<_i22.BankData>> fetchBankdatenMyBSSB(int? webloginId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBankdatenMyBSSB, [webloginId]),
            returnValue: _i10.Future<List<_i22.BankData>>.value(
              <_i22.BankData>[],
            ),
          )
          as _i10.Future<List<_i22.BankData>>);

  @override
  bool validateIBAN(String? iban) =>
      (super.noSuchMethod(
            Invocation.method(#validateIBAN, [iban]),
            returnValue: false,
          )
          as bool);

  @override
  _i10.Future<bool> registerBankData(_i22.BankData? bankData) =>
      (super.noSuchMethod(
            Invocation.method(#registerBankData, [bankData]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> deleteBankData(_i22.BankData? bankData) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBankData, [bankData]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<_i24.Verein>> fetchVereine() =>
      (super.noSuchMethod(
            Invocation.method(#fetchVereine, []),
            returnValue: _i10.Future<List<_i24.Verein>>.value(<_i24.Verein>[]),
          )
          as _i10.Future<List<_i24.Verein>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> fetchVereinFunktionaer(
    int? vereinId,
    int? funktyp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchVereinFunktionaer, [vereinId, funktyp]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<_i24.Verein>> fetchVerein(int? vereinsNr) =>
      (super.noSuchMethod(
            Invocation.method(#fetchVerein, [vereinsNr]),
            returnValue: _i10.Future<List<_i24.Verein>>.value(<_i24.Verein>[]),
          )
          as _i10.Future<List<_i24.Verein>>);

  @override
  _i10.Future<List<_i25.FremdeVerband>> fetchFremdeVerbaende(int? vereinsNr) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFremdeVerbaende, [vereinsNr]),
            returnValue: _i10.Future<List<_i25.FremdeVerband>>.value(
              <_i25.FremdeVerband>[],
            ),
          )
          as _i10.Future<List<_i25.FremdeVerband>>);

  @override
  _i10.Future<Map<String, dynamic>> createUser({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? passNumber,
    required String? personId,
    required String? verificationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #passNumber: passNumber,
              #personId: personId,
              #verificationToken: verificationToken,
            }),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>?> getUserByPasswordResetVerificationToken(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByPasswordResetVerificationToken, [
              token,
            ]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<Map<String, dynamic>?> getUserByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByEmail, [email]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<Map<String, dynamic>?> getUserByPersonId(String? personId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByPersonId, [personId]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<Map<String, dynamic>?> getUserByPassNumber(String? passNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByPassNumber, [passNumber]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<bool> verifyUser(String? verificationToken) =>
      (super.noSuchMethod(
            Invocation.method(#verifyUser, [verificationToken]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> deleteUserRegistration(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserRegistration, [id]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> softDeleteUser(String? personId) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteUser, [personId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<Map<String, dynamic>?> getUserByVerificationToken(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByVerificationToken, [token]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<bool> uploadProfilePhoto(String? userId, List<int>? photoBytes) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [userId, photoBytes]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> deleteProfilePhoto(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfilePhoto, [userId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<_i11.Uint8List?> getProfilePhoto(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilePhoto, [userId]),
            returnValue: _i10.Future<_i11.Uint8List?>.value(),
          )
          as _i10.Future<_i11.Uint8List?>);

  @override
  _i10.Future<void> createEmailValidationEntry({
    required String? personId,
    required String? email,
    required String? emailType,
    required String? verificationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEmailValidationEntry, [], {
              #personId: personId,
              #email: email,
              #emailType: emailType,
              #verificationToken: verificationToken,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>?> getEmailValidationByToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getEmailValidationByToken, [token]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<bool> markEmailValidationAsValidated(String? verificationToken) =>
      (super.noSuchMethod(
            Invocation.method(#markEmailValidationAsValidated, [
              verificationToken,
            ]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> sendEmailValidationNotifications({
    required String? personId,
    required String? email,
    required String? firstName,
    required String? lastName,
    required String? title,
    required String? emailType,
    required String? verificationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailValidationNotifications, [], {
              #personId: personId,
              #email: email,
              #firstName: firstName,
              #lastName: lastName,
              #title: title,
              #emailType: emailType,
              #verificationToken: verificationToken,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> sendSchulungAbmeldungEmail({
    required String? personId,
    required String? schulungName,
    required String? schulungDate,
    required String? firstName,
    required String? lastName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSchulungAbmeldungEmail, [], {
              #personId: personId,
              #schulungName: schulungName,
              #schulungDate: schulungDate,
              #firstName: firstName,
              #lastName: lastName,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> sendSchulungAnmeldungEmail({
    required String? personId,
    required String? schulungName,
    required String? schulungDate,
    required String? firstName,
    required String? lastName,
    required String? passnumber,
    required String? email,
    required int? schulungRegistered,
    required int? schulungTotal,
    String? location,
    DateTime? eventDateTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSchulungAnmeldungEmail, [], {
              #personId: personId,
              #schulungName: schulungName,
              #schulungDate: schulungDate,
              #firstName: firstName,
              #lastName: lastName,
              #passnumber: passnumber,
              #email: email,
              #schulungRegistered: schulungRegistered,
              #schulungTotal: schulungTotal,
              #location: location,
              #eventDateTime: eventDateTime,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String?> getFromEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getFromEmail, []),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<String?> getRegistrationSubject() =>
      (super.noSuchMethod(
            Invocation.method(#getRegistrationSubject, []),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<String?> getRegistrationContent() =>
      (super.noSuchMethod(
            Invocation.method(#getRegistrationContent, []),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<Map<String, dynamic>> sendEmail({
    required String? from,
    required String? recipient,
    required String? subject,
    String? htmlBody,
    int? emailId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmail, [], {
              #from: from,
              #recipient: recipient,
              #subject: subject,
              #htmlBody: htmlBody,
              #emailId: emailId,
            }),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<void> sendAccountCreationNotifications(
    String? personId,
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendAccountCreationNotifications, [
              personId,
              email,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<String>> getEmailAddressesByPersonId(String? personId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmailAddressesByPersonId, [personId]),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<void> sendStartingRightsChangeNotifications({
    required int? personId,
    required _i12.UserData? passdaten,
    required List<String>? userEmailAddresses,
    required List<String>? clubEmailAddresses,
    required List<_i15.ZweitmitgliedschaftData>? zweitmitgliedschaften,
    required _i13.PassdatenAkzeptOrAktiv? zveData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendStartingRightsChangeNotifications, [], {
              #personId: personId,
              #passdaten: passdaten,
              #userEmailAddresses: userEmailAddresses,
              #clubEmailAddresses: clubEmailAddresses,
              #zweitmitgliedschaften: zweitmitgliedschaften,
              #zveData: zveData,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i26.Result>> fetchResults(String? passnummer) =>
      (super.noSuchMethod(
            Invocation.method(#fetchResults, [passnummer]),
            returnValue: _i10.Future<List<_i26.Result>>.value(<_i26.Result>[]),
          )
          as _i10.Future<List<_i26.Result>>);

  @override
  _i10.Future<List<_i27.Gewinn>> fetchGewinne(int? jahr, String? passnummer) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGewinne, [jahr, passnummer]),
            returnValue: _i10.Future<List<_i27.Gewinn>>.value(<_i27.Gewinn>[]),
          )
          as _i10.Future<List<_i27.Gewinn>>);

  @override
  _i10.Future<List<_i27.Gewinn>> fetchGewinneEx(
    int? jahr,
    String? passnummer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGewinneEx, [jahr, passnummer]),
            returnValue: _i10.Future<List<_i27.Gewinn>>.value(<_i27.Gewinn>[]),
          )
          as _i10.Future<List<_i27.Gewinn>>);

  @override
  _i10.Future<bool> gewinneAbrufen({
    required List<int>? gewinnIDs,
    required String? iban,
    required String? passnummer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gewinneAbrufen, [], {
              #gewinnIDs: gewinnIDs,
              #iban: iban,
              #passnummer: passnummer,
            }),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> gewinneAbrufenEx({
    required List<int>? gewinnIDs,
    required String? iban,
    required String? passnummer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gewinneAbrufenEx, [], {
              #gewinnIDs: gewinnIDs,
              #iban: iban,
              #passnummer: passnummer,
            }),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<_i28.Bezirk>> fetchBezirke() =>
      (super.noSuchMethod(
            Invocation.method(#fetchBezirke, []),
            returnValue: _i10.Future<List<_i28.Bezirk>>.value(<_i28.Bezirk>[]),
          )
          as _i10.Future<List<_i28.Bezirk>>);

  @override
  _i10.Future<List<_i28.Bezirk>> fetchBezirk(int? bezirkNr) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBezirk, [bezirkNr]),
            returnValue: _i10.Future<List<_i28.Bezirk>>.value(<_i28.Bezirk>[]),
          )
          as _i10.Future<List<_i28.Bezirk>>);

  @override
  _i10.Future<List<_i28.BezirkSearchTriple>> fetchBezirkeforSearch() =>
      (super.noSuchMethod(
            Invocation.method(#fetchBezirkeforSearch, []),
            returnValue: _i10.Future<List<_i28.BezirkSearchTriple>>.value(
              <_i28.BezirkSearchTriple>[],
            ),
          )
          as _i10.Future<List<_i28.BezirkSearchTriple>>);

  @override
  _i10.Future<void> sendStartingRightsChangeNotificationsForPerson({
    required int? personId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendStartingRightsChangeNotificationsForPerson,
              [],
              {#personId: personId},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i3.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int? getInt(String? key, [String? section]) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key, section])) as int?);

  @override
  String? getString(String? key, [String? section]) =>
      (super.noSuchMethod(Invocation.method(#getString, [key, section]))
          as String?);

  @override
  List<String>? getList(String? key, [String? section]) =>
      (super.noSuchMethod(Invocation.method(#getList, [key, section]))
          as List<String>?);

  @override
  bool? getBool(String? key, [String? section]) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key, section]))
          as bool?);
}
