// Mocks generated by Mockito 5.4.6 from annotations
// in meinbssb/test/unit/screens/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i15;

import 'package:meinbssb/models/bank_data.dart' as _i19;
import 'package:meinbssb/models/bezirk_data.dart' as _i26;
import 'package:meinbssb/models/contact_data.dart' as _i14;
import 'package:meinbssb/models/disziplin_data.dart' as _i18;
import 'package:meinbssb/models/fremde_verband_data.dart' as _i21;
import 'package:meinbssb/models/gewinn_data.dart' as _i25;
import 'package:meinbssb/models/pass_data_zve_data.dart' as _i11;
import 'package:meinbssb/models/passdaten_akzept_or_aktiv_data.dart' as _i10;
import 'package:meinbssb/models/person_data.dart' as _i22;
import 'package:meinbssb/models/register_schulungen_teilnehmer_response_data.dart'
    as _i4;
import 'package:meinbssb/models/result_data.dart' as _i23;
import 'package:meinbssb/models/schulung_data.dart' as _i13;
import 'package:meinbssb/models/schulungsart_data.dart' as _i16;
import 'package:meinbssb/models/schulungstermin_data.dart' as _i17;
import 'package:meinbssb/models/user_data.dart' as _i9;
import 'package:meinbssb/models/verein_data.dart' as _i20;
import 'package:meinbssb/models/zweitmitgliedschaft_data.dart' as _i12;
import 'package:meinbssb/services/api/auth_service.dart' as _i5;
import 'package:meinbssb/services/api_service.dart' as _i8;
import 'package:meinbssb/services/core/config_service.dart' as _i24;
import 'package:meinbssb/services/core/email_service.dart' as _i27;
import 'package:meinbssb/services/core/image_service.dart' as _i3;
import 'package:meinbssb/services/core/postgrest_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostgrestService_0 extends _i1.SmartFake
    implements _i2.PostgrestService {
  _FakePostgrestService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageService_1 extends _i1.SmartFake implements _i3.ImageService {
  _FakeImageService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegisterSchulungenTeilnehmerResponse_3 extends _i1.SmartFake
    implements _i4.RegisterSchulungenTeilnehmerResponse {
  _FakeRegisterSchulungenTeilnehmerResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostgrestService get postgrestService => (super.noSuchMethod(
        Invocation.getter(#postgrestService),
        returnValue: _FakePostgrestService_0(
          this,
          Invocation.getter(#postgrestService),
        ),
      ) as _i2.PostgrestService);

  @override
  String generateVerificationToken() => (super.noSuchMethod(
        Invocation.method(
          #generateVerificationToken,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #generateVerificationToken,
            [],
          ),
        ),
      ) as String);

  @override
  _i7.Future<Map<String, dynamic>> register({
    required String? firstName,
    required String? lastName,
    required String? passNumber,
    required String? email,
    required String? birthDate,
    required String? zipCode,
    required String? personId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #passNumber: passNumber,
            #email: email,
            #birthDate: birthDate,
            #zipCode: zipCode,
            #personId: personId,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> changePassword(
    int? personId,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            personId,
            newPassword,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<dynamic> finalizeRegistration({
    required String? email,
    required String? password,
    required String? token,
    required String? personId,
    required String? passNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #finalizeRegistration,
          [],
          {
            #email: email,
            #password: password,
            #token: token,
            #personId: personId,
            #passNumber: passNumber,
          },
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> findePersonID2(
    String? nachname,
    String? passnummer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findePersonID2,
          [
            nachname,
            passnummer,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<String> fetchLoginEmail(String? passnummer) => (super.noSuchMethod(
        Invocation.method(
          #fetchLoginEmail,
          [passnummer],
        ),
        returnValue: _i7.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #fetchLoginEmail,
            [passnummer],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<bool> isTokenValid() => (super.noSuchMethod(
        Invocation.method(
          #isTokenValid,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<String> getPersonIDByPassnummer(String? passNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonIDByPassnummer,
          [passNumber],
        ),
        returnValue: _i7.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getPersonIDByPassnummer,
            [passNumber],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<Map<String, dynamic>> getPassDatenByPersonId(String? personId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPassDatenByPersonId,
          [personId],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<String> findePersonID(
    String? lastName,
    String? firstName,
    String? birthDate,
    String? passNumber,
    String? zipCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findePersonID,
          [
            lastName,
            firstName,
            birthDate,
            passNumber,
            zipCode,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #findePersonID,
            [
              lastName,
              firstName,
              birthDate,
              passNumber,
              zipCode,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<Map<String, dynamic>> resetPasswordStep1(String? passNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPasswordStep1,
          [passNumber],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> resetPasswordStep2(
    String? token,
    String? personId,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPasswordStep2,
          [
            token,
            personId,
            newPassword,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i8.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ImageService get imageService => (super.noSuchMethod(
        Invocation.getter(#imageService),
        returnValue: _FakeImageService_1(
          this,
          Invocation.getter(#imageService),
        ),
      ) as _i3.ImageService);

  @override
  _i7.Future<bool> hasInternet() => (super.noSuchMethod(
        Invocation.method(
          #hasInternet,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  Duration getCacheExpirationDuration() => (super.noSuchMethod(
        Invocation.method(
          #getCacheExpirationDuration,
          [],
        ),
        returnValue: _FakeDuration_2(
          this,
          Invocation.method(
            #getCacheExpirationDuration,
            [],
          ),
        ),
      ) as Duration);

  @override
  _i7.Future<Map<String, dynamic>> register({
    required String? firstName,
    required String? lastName,
    required String? passNumber,
    required String? email,
    required String? birthDate,
    required String? zipCode,
    required String? personId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #passNumber: passNumber,
            #email: email,
            #birthDate: birthDate,
            #zipCode: zipCode,
            #personId: personId,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> passwordReset(String? passNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #passwordReset,
          [passNumber],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> finalizeResetPassword(
    String? token,
    String? personId,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #finalizeResetPassword,
          [
            token,
            personId,
            newPassword,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>?> getUserByPasswordResetVerificationToken(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByPasswordResetVerificationToken,
          [token],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<Map<String, dynamic>> changePassword(
    int? personId,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            personId,
            newPassword,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i9.UserData?> fetchPassdaten(int? personId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPassdaten,
          [personId],
        ),
        returnValue: _i7.Future<_i9.UserData?>.value(),
      ) as _i7.Future<_i9.UserData?>);

  @override
  _i7.Future<_i10.PassdatenAkzeptOrAktiv?>
      fetchPassdatenAkzeptierterOderAktiverPass(int? personId) =>
          (super.noSuchMethod(
            Invocation.method(
              #fetchPassdatenAkzeptierterOderAktiverPass,
              [personId],
            ),
            returnValue: _i7.Future<_i10.PassdatenAkzeptOrAktiv?>.value(),
          ) as _i7.Future<_i10.PassdatenAkzeptOrAktiv?>);

  @override
  _i7.Future<bool> postBSSBAppPassantrag(
    Map<int, Map<String, int?>>? secondColumns,
    int? passdatenId,
    int? personId,
    int? erstVereinId,
    int? digitalerPass,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postBSSBAppPassantrag,
          [
            secondColumns,
            passdatenId,
            personId,
            erstVereinId,
            digitalerPass,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i11.PassDataZVE>> fetchPassdatenZVE(
    int? passdatenId,
    int? personId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPassdatenZVE,
          [
            passdatenId,
            personId,
          ],
        ),
        returnValue:
            _i7.Future<List<_i11.PassDataZVE>>.value(<_i11.PassDataZVE>[]),
      ) as _i7.Future<List<_i11.PassDataZVE>>);

  @override
  _i7.Future<bool> updateKritischeFelderUndAdresse(_i9.UserData? userData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateKritischeFelderUndAdresse,
          [userData],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i12.ZweitmitgliedschaftData>> fetchZweitmitgliedschaften(
          int? personId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchZweitmitgliedschaften,
          [personId],
        ),
        returnValue: _i7.Future<List<_i12.ZweitmitgliedschaftData>>.value(
            <_i12.ZweitmitgliedschaftData>[]),
      ) as _i7.Future<List<_i12.ZweitmitgliedschaftData>>);

  @override
  _i7.Future<List<_i12.ZweitmitgliedschaftData>> fetchZweitmitgliedschaftenZVE(
    int? personId,
    int? passStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchZweitmitgliedschaftenZVE,
          [
            personId,
            passStatus,
          ],
        ),
        returnValue: _i7.Future<List<_i12.ZweitmitgliedschaftData>>.value(
            <_i12.ZweitmitgliedschaftData>[]),
      ) as _i7.Future<List<_i12.ZweitmitgliedschaftData>>);

  @override
  _i7.Future<List<_i13.Schulung>> fetchAbsolvierteSchulungen(int? personId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAbsolvierteSchulungen,
          [personId],
        ),
        returnValue: _i7.Future<List<_i13.Schulung>>.value(<_i13.Schulung>[]),
      ) as _i7.Future<List<_i13.Schulung>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> fetchKontakte(int? personId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchKontakte,
          [personId],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<bool> addKontakt(_i14.Contact? contact) => (super.noSuchMethod(
        Invocation.method(
          #addKontakt,
          [contact],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteKontakt(_i14.Contact? contact) => (super.noSuchMethod(
        Invocation.method(
          #deleteKontakt,
          [contact],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i15.Uint8List> fetchSchuetzenausweis(int? personId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSchuetzenausweis,
          [personId],
        ),
        returnValue: _i7.Future<_i15.Uint8List>.value(_i15.Uint8List(0)),
      ) as _i7.Future<_i15.Uint8List>);

  @override
  _i7.Future<List<_i16.Schulungsart>> fetchSchulungsarten() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSchulungsarten,
          [],
        ),
        returnValue:
            _i7.Future<List<_i16.Schulungsart>>.value(<_i16.Schulungsart>[]),
      ) as _i7.Future<List<_i16.Schulungsart>>);

  @override
  _i7.Future<List<_i17.Schulungstermin>> fetchAngemeldeteSchulungen(
    int? personId,
    String? abDatum,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAngemeldeteSchulungen,
          [
            personId,
            abDatum,
          ],
        ),
        returnValue: _i7.Future<List<_i17.Schulungstermin>>.value(
            <_i17.Schulungstermin>[]),
      ) as _i7.Future<List<_i17.Schulungstermin>>);

  @override
  _i7.Future<List<_i17.Schulungstermin>> fetchSchulungstermine(
    String? abDatum,
    String? webGruppe,
    String? bezirk,
    String? fuerVerlaengerung,
    String? fuerVuelVerlaengerung,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSchulungstermine,
          [
            abDatum,
            webGruppe,
            bezirk,
            fuerVerlaengerung,
            fuerVuelVerlaengerung,
          ],
        ),
        returnValue: _i7.Future<List<_i17.Schulungstermin>>.value(
            <_i17.Schulungstermin>[]),
      ) as _i7.Future<List<_i17.Schulungstermin>>);

  @override
  _i7.Future<_i17.Schulungstermin?> fetchSchulungstermin(
          String? schulungenTerminID) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSchulungstermin,
          [schulungenTerminID],
        ),
        returnValue: _i7.Future<_i17.Schulungstermin?>.value(),
      ) as _i7.Future<_i17.Schulungstermin?>);

  @override
  _i7.Future<bool> unregisterFromSchulung(int? schulungenTeilnehmerID) =>
      (super.noSuchMethod(
        Invocation.method(
          #unregisterFromSchulung,
          [schulungenTeilnehmerID],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> registerFromSchulung(
    int? personId,
    int? schulungId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerFromSchulung,
          [
            personId,
            schulungId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i18.Disziplin>> fetchDisziplinen() => (super.noSuchMethod(
        Invocation.method(
          #fetchDisziplinen,
          [],
        ),
        returnValue: _i7.Future<List<_i18.Disziplin>>.value(<_i18.Disziplin>[]),
      ) as _i7.Future<List<_i18.Disziplin>>);

  @override
  _i7.Future<List<_i19.BankData>> fetchBankData(int? webloginId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchBankData,
          [webloginId],
        ),
        returnValue: _i7.Future<List<_i19.BankData>>.value(<_i19.BankData>[]),
      ) as _i7.Future<List<_i19.BankData>>);

  @override
  _i7.Future<bool> registerBankData(_i19.BankData? bankData) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerBankData,
          [bankData],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteBankData(_i19.BankData? bankData) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBankData,
          [bankData],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i20.Verein>> fetchVereine() => (super.noSuchMethod(
        Invocation.method(
          #fetchVereine,
          [],
        ),
        returnValue: _i7.Future<List<_i20.Verein>>.value(<_i20.Verein>[]),
      ) as _i7.Future<List<_i20.Verein>>);

  @override
  _i7.Future<List<_i20.Verein>> fetchVerein(int? vereinsNr) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchVerein,
          [vereinsNr],
        ),
        returnValue: _i7.Future<List<_i20.Verein>>.value(<_i20.Verein>[]),
      ) as _i7.Future<List<_i20.Verein>>);

  @override
  _i7.Future<List<_i21.FremdeVerband>> fetchFremdeVerbaende(int? vereinsNr) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchFremdeVerbaende,
          [vereinsNr],
        ),
        returnValue:
            _i7.Future<List<_i21.FremdeVerband>>.value(<_i21.FremdeVerband>[]),
      ) as _i7.Future<List<_i21.FremdeVerband>>);

  @override
  _i7.Future<_i4.RegisterSchulungenTeilnehmerResponse>
      registerSchulungenTeilnehmer({
    required int? schulungTerminId,
    required _i9.UserData? user,
    required String? email,
    required String? telefon,
    required _i19.BankData? bankData,
    required List<Map<String, dynamic>>? felderArray,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #registerSchulungenTeilnehmer,
              [],
              {
                #schulungTerminId: schulungTerminId,
                #user: user,
                #email: email,
                #telefon: telefon,
                #bankData: bankData,
                #felderArray: felderArray,
              },
            ),
            returnValue:
                _i7.Future<_i4.RegisterSchulungenTeilnehmerResponse>.value(
                    _FakeRegisterSchulungenTeilnehmerResponse_3(
              this,
              Invocation.method(
                #registerSchulungenTeilnehmer,
                [],
                {
                  #schulungTerminId: schulungTerminId,
                  #user: user,
                  #email: email,
                  #telefon: telefon,
                  #bankData: bankData,
                  #felderArray: felderArray,
                },
              ),
            )),
          ) as _i7.Future<_i4.RegisterSchulungenTeilnehmerResponse>);

  @override
  _i7.Future<int> findePersonID2(
    String? nachname,
    String? passnummer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findePersonID2,
          [
            nachname,
            passnummer,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> clearSchulungenCache(int? personId) => (super.noSuchMethod(
        Invocation.method(
          #clearSchulungenCache,
          [personId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAllSchulungenCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSchulungenCache,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearPassdatenCache(int? personId) => (super.noSuchMethod(
        Invocation.method(
          #clearPassdatenCache,
          [personId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendSchulungAbmeldungEmail({
    required String? personId,
    required String? schulungName,
    required String? schulungDate,
    required String? firstName,
    required String? lastName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSchulungAbmeldungEmail,
          [],
          {
            #personId: personId,
            #schulungName: schulungName,
            #schulungDate: schulungDate,
            #firstName: firstName,
            #lastName: lastName,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendSchulungAnmeldungEmail({
    required String? personId,
    required String? schulungName,
    required String? schulungDate,
    required String? firstName,
    required String? lastName,
    required String? passnumber,
    required String? email,
    required int? schulungRegistered,
    required int? schulungTotal,
    String? location,
    DateTime? eventDateTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSchulungAnmeldungEmail,
          [],
          {
            #personId: personId,
            #schulungName: schulungName,
            #schulungDate: schulungDate,
            #firstName: firstName,
            #lastName: lastName,
            #passnumber: passnumber,
            #email: email,
            #schulungRegistered: schulungRegistered,
            #schulungTotal: schulungTotal,
            #location: location,
            #eventDateTime: eventDateTime,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAllPassdatenCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllPassdatenCache,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearDisziplinenCache() => (super.noSuchMethod(
        Invocation.method(
          #clearDisziplinenCache,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i22.Person>> fetchAdresseVonPersonID(int? personId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAdresseVonPersonID,
          [personId],
        ),
        returnValue: _i7.Future<List<_i22.Person>>.value(<_i22.Person>[]),
      ) as _i7.Future<List<_i22.Person>>);

  @override
  bool validateIBAN(String? iban) => (super.noSuchMethod(
        Invocation.method(
          #validateIBAN,
          [iban],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<Map<String, dynamic>> createUser({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? passNumber,
    required String? personId,
    required String? verificationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #passNumber: passNumber,
            #personId: personId,
            #verificationToken: verificationToken,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>?> getUserByEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByEmail,
          [email],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<Map<String, dynamic>?> getUserByPersonId(String? personId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByPersonId,
          [personId],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<Map<String, dynamic>?> getUserByPassNumber(String? passNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByPassNumber,
          [passNumber],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<bool> verifyUser(String? verificationToken) => (super.noSuchMethod(
        Invocation.method(
          #verifyUser,
          [verificationToken],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteUserRegistration(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteUserRegistration,
          [id],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<Map<String, dynamic>?> getUserByVerificationToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByVerificationToken,
          [token],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<bool> uploadProfilePhoto(
    String? userId,
    List<int>? photoBytes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfilePhoto,
          [
            userId,
            photoBytes,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteProfilePhoto(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProfilePhoto,
          [userId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i15.Uint8List?> getProfilePhoto(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfilePhoto,
          [userId],
        ),
        returnValue: _i7.Future<_i15.Uint8List?>.value(),
      ) as _i7.Future<_i15.Uint8List?>);

  @override
  _i7.Future<String?> getFromEmail() => (super.noSuchMethod(
        Invocation.method(
          #getFromEmail,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getRegistrationSubject() => (super.noSuchMethod(
        Invocation.method(
          #getRegistrationSubject,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getRegistrationContent() => (super.noSuchMethod(
        Invocation.method(
          #getRegistrationContent,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<Map<String, dynamic>> sendEmail({
    required String? from,
    required String? recipient,
    required String? subject,
    String? htmlBody,
    int? emailId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmail,
          [],
          {
            #from: from,
            #recipient: recipient,
            #subject: subject,
            #htmlBody: htmlBody,
            #emailId: emailId,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> sendAccountCreationNotifications(
    String? personId,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAccountCreationNotifications,
          [
            personId,
            email,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i23.Result>> fetchResults(
    String? passnummer,
    _i24.ConfigService? configService,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchResults,
          [
            passnummer,
            configService,
          ],
        ),
        returnValue: _i7.Future<List<_i23.Result>>.value(<_i23.Result>[]),
      ) as _i7.Future<List<_i23.Result>>);

  @override
  _i7.Future<List<_i25.Gewinn>> fetchGewinne(
    int? jahr,
    String? passnummer,
    _i24.ConfigService? configService,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGewinne,
          [
            jahr,
            passnummer,
            configService,
          ],
        ),
        returnValue: _i7.Future<List<_i25.Gewinn>>.value(<_i25.Gewinn>[]),
      ) as _i7.Future<List<_i25.Gewinn>>);

  @override
  _i7.Future<List<_i26.Bezirk>> fetchBezirke() => (super.noSuchMethod(
        Invocation.method(
          #fetchBezirke,
          [],
        ),
        returnValue: _i7.Future<List<_i26.Bezirk>>.value(<_i26.Bezirk>[]),
      ) as _i7.Future<List<_i26.Bezirk>>);

  @override
  _i7.Future<List<_i26.Bezirk>> fetchBezirk(int? bezirkNr) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchBezirk,
          [bezirkNr],
        ),
        returnValue: _i7.Future<List<_i26.Bezirk>>.value(<_i26.Bezirk>[]),
      ) as _i7.Future<List<_i26.Bezirk>>);

  @override
  _i7.Future<List<_i26.BezirkSearchTriple>> fetchBezirkeforSearch() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchBezirkeforSearch,
          [],
        ),
        returnValue: _i7.Future<List<_i26.BezirkSearchTriple>>.value(
            <_i26.BezirkSearchTriple>[]),
      ) as _i7.Future<List<_i26.BezirkSearchTriple>>);

  @override
  _i7.Future<void> createEmailValidationEntry({
    required String? personId,
    required String? email,
    required String? emailType,
    required String? verificationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEmailValidationEntry,
          [],
          {
            #personId: personId,
            #email: email,
            #emailType: emailType,
            #verificationToken: verificationToken,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> getEmailValidationByToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmailValidationByToken,
          [token],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<bool> markEmailValidationAsValidated(String? verificationToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #markEmailValidationAsValidated,
          [verificationToken],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> sendEmailValidationNotifications({
    required String? personId,
    required String? email,
    required String? firstName,
    required String? lastName,
    required String? title,
    required String? emailType,
    required String? verificationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailValidationNotifications,
          [],
          {
            #personId: personId,
            #email: email,
            #firstName: firstName,
            #lastName: lastName,
            #title: title,
            #emailType: emailType,
            #verificationToken: verificationToken,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendStartingRightsChangeNotifications(
          {required int? personId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendStartingRightsChangeNotifications,
          [],
          {#personId: personId},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [EmailService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailService extends _i1.Mock implements _i27.EmailService {
  MockEmailService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<Map<String, dynamic>> sendEmail({
    required String? sender,
    required String? recipient,
    required String? subject,
    String? htmlBody,
    int? emailId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmail,
          [],
          {
            #sender: sender,
            #recipient: recipient,
            #subject: subject,
            #htmlBody: htmlBody,
            #emailId: emailId,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<String?> getRegistrationSubject() => (super.noSuchMethod(
        Invocation.method(
          #getRegistrationSubject,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getRegistrationContent() => (super.noSuchMethod(
        Invocation.method(
          #getRegistrationContent,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getVerificationBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #getVerificationBaseUrl,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getWelcomeSubject() => (super.noSuchMethod(
        Invocation.method(
          #getWelcomeSubject,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getWelcomeContent() => (super.noSuchMethod(
        Invocation.method(
          #getWelcomeContent,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getFromEmail() => (super.noSuchMethod(
        Invocation.method(
          #getFromEmail,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getAccountCreatedSubject() => (super.noSuchMethod(
        Invocation.method(
          #getAccountCreatedSubject,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getAccountCreatedContent() => (super.noSuchMethod(
        Invocation.method(
          #getAccountCreatedContent,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getPasswordResetSubject() => (super.noSuchMethod(
        Invocation.method(
          #getPasswordResetSubject,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getPasswordResetContent() => (super.noSuchMethod(
        Invocation.method(
          #getPasswordResetContent,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getSchulungAbmeldungSubject() => (super.noSuchMethod(
        Invocation.method(
          #getSchulungAbmeldungSubject,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getSchulungAbmeldungContent() => (super.noSuchMethod(
        Invocation.method(
          #getSchulungAbmeldungContent,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getSchulungAnmeldungSubject() => (super.noSuchMethod(
        Invocation.method(
          #getSchulungAnmeldungSubject,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getSchulungAnmeldungContent() => (super.noSuchMethod(
        Invocation.method(
          #getSchulungAnmeldungContent,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getEmailValidationSubject() => (super.noSuchMethod(
        Invocation.method(
          #getEmailValidationSubject,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getEmailValidationContent() => (super.noSuchMethod(
        Invocation.method(
          #getEmailValidationContent,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getStartingRightsChangeSubject() => (super.noSuchMethod(
        Invocation.method(
          #getStartingRightsChangeSubject,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getStartingRightsChangeContent() => (super.noSuchMethod(
        Invocation.method(
          #getStartingRightsChangeContent,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<List<String>> getEmailAddressesByPersonId(String? personId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmailAddressesByPersonId,
          [personId],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<void> sendAccountCreationNotifications(
    String? personId,
    String? registeredEmail,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAccountCreationNotifications,
          [
            personId,
            registeredEmail,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendPasswordResetNotifications(
    Map<String, dynamic>? passData,
    List<String>? emailAddresses,
    String? verificationLink,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetNotifications,
          [
            passData,
            emailAddresses,
            verificationLink,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendSchulungAbmeldungEmail({
    required String? personId,
    required String? schulungName,
    required String? schulungDate,
    required String? firstName,
    required String? lastName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSchulungAbmeldungEmail,
          [],
          {
            #personId: personId,
            #schulungName: schulungName,
            #schulungDate: schulungDate,
            #firstName: firstName,
            #lastName: lastName,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendRegistrationEmail({
    required String? email,
    required String? firstName,
    required String? lastName,
    required String? verificationLink,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendRegistrationEmail,
          [],
          {
            #email: email,
            #firstName: firstName,
            #lastName: lastName,
            #verificationLink: verificationLink,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendSchulungAnmeldungEmail({
    required String? personId,
    required String? schulungName,
    required String? schulungDate,
    required String? firstName,
    required String? lastName,
    required String? passnumber,
    required String? email,
    required int? schulungRegistered,
    required int? schulungTotal,
    String? location,
    DateTime? eventDateTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSchulungAnmeldungEmail,
          [],
          {
            #personId: personId,
            #schulungName: schulungName,
            #schulungDate: schulungDate,
            #firstName: firstName,
            #lastName: lastName,
            #passnumber: passnumber,
            #email: email,
            #schulungRegistered: schulungRegistered,
            #schulungTotal: schulungTotal,
            #location: location,
            #eventDateTime: eventDateTime,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendEmailValidationNotifications({
    required String? personId,
    required String? email,
    required String? firstName,
    required String? lastName,
    required String? title,
    required String? emailType,
    required String? verificationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailValidationNotifications,
          [],
          {
            #personId: personId,
            #email: email,
            #firstName: firstName,
            #lastName: lastName,
            #title: title,
            #emailType: emailType,
            #verificationToken: verificationToken,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendStartingRightsChangeNotifications({
    required int? personId,
    required _i9.UserData? passdaten,
    required List<String>? userEmailAddresses,
    required List<String>? clubEmailAddresses,
    required List<_i12.ZweitmitgliedschaftData>? zweitmitgliedschaften,
    required _i10.PassdatenAkzeptOrAktiv? zveData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendStartingRightsChangeNotifications,
          [],
          {
            #personId: personId,
            #passdaten: passdaten,
            #userEmailAddresses: userEmailAddresses,
            #clubEmailAddresses: clubEmailAddresses,
            #zweitmitgliedschaften: zweitmitgliedschaften,
            #zveData: zveData,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
